# Generated by Django 5.0.4 on 2024-05-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.TextField()),
                ('date_field', models.DateField()),
                ('parameters_json', models.JSONField()),
            ],
        ),
    ]
