# Generated by Django 5.0.4 on 2024-05-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PastParameters',
            new_name='PastParameter',
        ),
    ]
