# Generated by Django 5.0.4 on 2024-10-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_app', '0002_databastconnections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatabastConnections',
            new_name='DatabaseConnection',
        ),
    ]
