# Generated by Django 5.0.4 on 2024-11-01 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_app', '0003_rename_databastconnections_databaseconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='RanReportParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.TextField()),
                ('ran_on_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ran_report_parameters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
