# Generated by Django 5.0.4 on 2024-11-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_app', '0004_ranreportparameter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PastParameter',
        ),
    ]
