# Generated by Django 5.0.4 on 2024-11-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_app', '0005_delete_pastparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_database_alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
