# Generated by Django 5.0.4 on 2024-11-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_app', '0006_user_active_database_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='port',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='driver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
