# Generated by Django 5.0.4 on 2024-11-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_app', '0007_databaseconnection_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='driver',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='port',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
