# Generated by Django 5.0.4 on 2024-11-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_app', '0008_alter_databaseconnection_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='driver',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='port',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
