# Generated by Django 5.0.4 on 2024-11-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_app', '0009_alter_databaseconnection_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranreportparameter',
            name='database_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
